// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RotinikApi.Data;

#nullable disable

namespace RotinikApi.Migrations
{
    [DbContext(typeof(RotinikContext))]
    [Migration("20260512203327_AddRoutinesAndTasks")]
    partial class AddRoutinesAndTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RotinikApi.Models.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsTemplate")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Theme")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Start your day with clarity and energy.",
                            IsTemplate = true,
                            Name = "Morning Routine",
                            Theme = "Morning"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Stay active and build healthy habits.",
                            IsTemplate = true,
                            Name = "Fitness Routine",
                            Theme = "Fitness"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Sharpen your focus and learn effectively.",
                            IsTemplate = true,
                            Name = "Study Routine",
                            Theme = "Study"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Relax and prepare for restful sleep.",
                            IsTemplate = true,
                            Name = "Evening Wind-Down",
                            Theme = "Evening"
                        });
                });

            modelBuilder.Entity("RotinikApi.Models.RoutineExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("UserId");

                    b.ToTable("RoutineExecutions");
                });

            modelBuilder.Entity("RotinikApi.Models.RoutineTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.HasIndex("TaskId");

                    b.ToTable("RoutineTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsCompleted = false,
                            Order = 0,
                            RoutineId = 1,
                            TaskId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsCompleted = false,
                            Order = 1,
                            RoutineId = 1,
                            TaskId = 2
                        },
                        new
                        {
                            Id = 3,
                            IsCompleted = false,
                            Order = 2,
                            RoutineId = 1,
                            TaskId = 3
                        },
                        new
                        {
                            Id = 4,
                            IsCompleted = false,
                            Order = 0,
                            RoutineId = 2,
                            TaskId = 4
                        },
                        new
                        {
                            Id = 5,
                            IsCompleted = false,
                            Order = 1,
                            RoutineId = 2,
                            TaskId = 5
                        },
                        new
                        {
                            Id = 6,
                            IsCompleted = false,
                            Order = 2,
                            RoutineId = 2,
                            TaskId = 6
                        },
                        new
                        {
                            Id = 7,
                            IsCompleted = false,
                            Order = 0,
                            RoutineId = 3,
                            TaskId = 7
                        },
                        new
                        {
                            Id = 8,
                            IsCompleted = false,
                            Order = 1,
                            RoutineId = 3,
                            TaskId = 8
                        },
                        new
                        {
                            Id = 9,
                            IsCompleted = false,
                            Order = 2,
                            RoutineId = 3,
                            TaskId = 9
                        },
                        new
                        {
                            Id = 10,
                            IsCompleted = false,
                            Order = 0,
                            RoutineId = 4,
                            TaskId = 10
                        },
                        new
                        {
                            Id = 11,
                            IsCompleted = false,
                            Order = 1,
                            RoutineId = 4,
                            TaskId = 11
                        },
                        new
                        {
                            Id = 12,
                            IsCompleted = false,
                            Order = 2,
                            RoutineId = 4,
                            TaskId = 12
                        });
                });

            modelBuilder.Entity("RotinikApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RotinikApi.Models.UserTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Tasks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hydrate right after waking up.",
                            EstimatedMinutes = 2,
                            Frequency = 0,
                            Title = "Drink a glass of water",
                            Type = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Gentle full-body stretch.",
                            EstimatedMinutes = 10,
                            Frequency = 0,
                            Title = "10-minute stretching",
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write down your top 3 goals.",
                            EstimatedMinutes = 5,
                            Frequency = 0,
                            Title = "Review daily goals",
                            Type = 2
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Light jog or brisk walk.",
                            EstimatedMinutes = 15,
                            Frequency = 0,
                            Title = "Warm-up run",
                            Type = 2
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Focus on one muscle group.",
                            EstimatedMinutes = 45,
                            Frequency = 0,
                            Title = "Strength training",
                            Type = 3
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Cool down and improve flexibility.",
                            EstimatedMinutes = 10,
                            Frequency = 0,
                            Title = "Post-workout stretch",
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Reinforce memory through recall.",
                            EstimatedMinutes = 15,
                            Frequency = 0,
                            Title = "Review yesterday's notes",
                            Type = 2
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "No distractions, full focus.",
                            EstimatedMinutes = 50,
                            Frequency = 0,
                            Title = "Deep-focus study block",
                            Type = 3
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Apply what you learned.",
                            EstimatedMinutes = 30,
                            Frequency = 0,
                            Title = "Practice problems",
                            Type = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Write 3 wins and 1 improvement.",
                            EstimatedMinutes = 10,
                            Frequency = 0,
                            Title = "Reflect on the day",
                            Type = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Unplug and read something enriching.",
                            EstimatedMinutes = 20,
                            Frequency = 0,
                            Title = "Read for 20 minutes",
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Set intentions for the next day.",
                            EstimatedMinutes = 10,
                            Frequency = 0,
                            Title = "Prepare tomorrow's plan",
                            Type = 2
                        });
                });

            modelBuilder.Entity("RotinikApi.Models.Routine", b =>
                {
                    b.HasOne("RotinikApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RotinikApi.Models.RoutineExecution", b =>
                {
                    b.HasOne("RotinikApi.Models.Routine", "Routine")
                        .WithMany("Executions")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotinikApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RotinikApi.Models.RoutineTask", b =>
                {
                    b.HasOne("RotinikApi.Models.Routine", "Routine")
                        .WithMany("RoutineTasks")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RotinikApi.Models.UserTask", "Task")
                        .WithMany("RoutineTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Routine");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("RotinikApi.Models.UserTask", b =>
                {
                    b.HasOne("RotinikApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("RotinikApi.Models.Routine", b =>
                {
                    b.Navigation("Executions");

                    b.Navigation("RoutineTasks");
                });

            modelBuilder.Entity("RotinikApi.Models.UserTask", b =>
                {
                    b.Navigation("RoutineTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
