// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Rotinik.Core.Data;

#nullable disable

namespace Rotinik.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608014947_AddSpaceShopItems")]
    partial class AddSpaceShopItems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Medal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("TargetValue")
                        .HasColumnType("integer");

                    b.Property<int>("TriggerType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Medals", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Medals.UserMedal", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("MedalId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "MedalId");

                    b.HasIndex("MedalId");

                    b.ToTable("UserMedals", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Routines.Routine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("daily");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Routines", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Shop.ShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("Discount")
                        .HasColumnType("double precision");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Price")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.ToTable("ShopItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "avatar",
                            Description = "O inicio de uma grande jornada espacial.",
                            Icon = "👨‍🚀",
                            IsNew = true,
                            Name = "Astronauta Novato",
                            Price = 100,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 2,
                            Category = "avatar",
                            Description = "Um visitante de outra galaxia.",
                            Icon = "👽",
                            IsNew = false,
                            Name = "Extraterrestre",
                            Price = 200,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 3,
                            Category = "avatar",
                            Description = "Tecnologia avancada de marte.",
                            Icon = "🤖",
                            IsNew = true,
                            Name = "Robo Marciano",
                            Price = 300,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 4,
                            Category = "avatar",
                            Description = "Lider da frota espacial.",
                            Icon = "🧑‍✈️",
                            IsNew = false,
                            Name = "Comandante Estelar",
                            Price = 500,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 5,
                            Category = "avatar",
                            Description = "O puro poder do universo.",
                            Icon = "🌌",
                            IsNew = false,
                            Name = "Entidade Cosmica",
                            Price = 1000,
                            Rarity = "legendary"
                        },
                        new
                        {
                            Id = 6,
                            Category = "border",
                            Description = "Poeira espacial rodando seu perfil.",
                            Icon = "2px dashed #9ca3af",
                            IsNew = false,
                            Name = "Borda de Asteroides",
                            Price = 150,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 7,
                            Category = "border",
                            Description = "Um aro de luz de orbita baixa.",
                            Icon = "3px solid #38bdf8",
                            IsNew = true,
                            Name = "Borda Neon Orbita",
                            Price = 250,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 8,
                            Category = "border",
                            Description = "A propulsao do foguete no seu perfil.",
                            Icon = "3px solid #f97316",
                            IsNew = false,
                            Name = "Borda Chama de Foguete",
                            Price = 350,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 9,
                            Category = "border",
                            Description = "Uma aura cosmica misteriosa.",
                            Icon = "4px double #8b5cf6",
                            IsNew = true,
                            Name = "Borda Materia Escura",
                            Price = 600,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 10,
                            Category = "border",
                            Description = "O brilho intenso de uma estrela explodindo.",
                            Icon = "4px solid #fbbf24",
                            IsNew = false,
                            Name = "Borda Supernova",
                            Price = 1200,
                            Rarity = "legendary"
                        },
                        new
                        {
                            Id = 11,
                            Category = "level_icon",
                            Description = "Orbita basica de comunicacao.",
                            Icon = "📡",
                            IsNew = false,
                            Name = "Satelite",
                            Price = 100,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 12,
                            Category = "level_icon",
                            Description = "Exploracao do nosso vizinho.",
                            Icon = "🌕",
                            IsNew = false,
                            Name = "Lua",
                            Price = 200,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 13,
                            Category = "level_icon",
                            Description = "Voando alem das nuvens.",
                            Icon = "🚀",
                            IsNew = true,
                            Name = "Foguete Espacial",
                            Price = 400,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 14,
                            Category = "level_icon",
                            Description = "Uma nave nao identificada.",
                            Icon = "🛸",
                            IsNew = false,
                            Name = "Disco Voador",
                            Price = 700,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 15,
                            Category = "level_icon",
                            Description = "Um rastro iluminado e magico.",
                            Icon = "🌠",
                            IsNew = true,
                            Name = "Estrela Cadente",
                            Price = 1500,
                            Rarity = "legendary"
                        },
                        new
                        {
                            Id = 16,
                            Category = "background",
                            Description = "Cores cinzas do solo lunar.",
                            Icon = "linear-gradient(135deg, #1f2937, #374151)",
                            IsNew = false,
                            Name = "Fundo Superficie Lunar",
                            Price = 200,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 17,
                            Category = "background",
                            Description = "Uma vista para as estrelas noturnas.",
                            Icon = "linear-gradient(135deg, #0f172a, #1e1b4b)",
                            IsNew = false,
                            Name = "Fundo Ceu Estrelado",
                            Price = 400,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 18,
                            Category = "background",
                            Description = "Uma mistura quente de gases estelares.",
                            Icon = "linear-gradient(135deg, #7c2d12, #9a3412)",
                            IsNew = true,
                            Name = "Fundo Nebulosa Solar",
                            Price = 600,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 19,
                            Category = "background",
                            Description = "Sugando toda a luz do universo.",
                            Icon = "radial-gradient(circle, #000000 0%, #171717 100%)",
                            IsNew = false,
                            Name = "Fundo Buraco Negro",
                            Price = 900,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 20,
                            Category = "background",
                            Description = "Cores cosmicas brilhantes.",
                            Icon = "linear-gradient(135deg, #1e1b4b 0%, #4c1d95 50%, #0ea5e9 100%)",
                            IsNew = true,
                            Name = "Fundo Aurora Boreal Estelar",
                            Price = 2000,
                            Rarity = "legendary"
                        },
                        new
                        {
                            Id = 21,
                            Category = "navbar",
                            Description = "Metal basico de naves.",
                            Icon = "#1e293b",
                            IsNew = false,
                            Name = "Nav Bar Padrao Espacial",
                            Price = 150,
                            Rarity = "common"
                        },
                        new
                        {
                            Id = 22,
                            Category = "navbar",
                            Description = "Brilho roxo espacial profundo.",
                            Icon = "#4c1d95",
                            IsNew = true,
                            Name = "Nav Bar Ametista Galactica",
                            Price = 300,
                            Rarity = "rare"
                        },
                        new
                        {
                            Id = 23,
                            Category = "navbar",
                            Description = "Vermelho e quente como o planeta.",
                            Icon = "#9f1239",
                            IsNew = false,
                            Name = "Nav Bar Marte",
                            Price = 500,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 24,
                            Category = "navbar",
                            Description = "Um tom cosmico azul escuro.",
                            Icon = "#0f172a",
                            IsNew = false,
                            Name = "Nav Bar Via Lactea",
                            Price = 800,
                            Rarity = "epic"
                        },
                        new
                        {
                            Id = 25,
                            Category = "navbar",
                            Description = "O brilho maximo da tecnologia.",
                            Icon = "linear-gradient(90deg, #6d28d9, #2563eb, #db2777)",
                            IsNew = true,
                            Name = "Nav Bar Velocidade da Luz",
                            Price = 2500,
                            Rarity = "legendary"
                        });
                });

            modelBuilder.Entity("Rotinik.Features.Shop.UserShopItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("PurchasedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ShopItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ShopItemId");

                    b.HasIndex("UserId");

                    b.ToTable("UserShopItems");
                });

            modelBuilder.Entity("Rotinik.Features.Statistics.DailyUserSummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("RoutinesCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("TasksCompleted")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique();

                    b.ToTable("DailyUserSummaries", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Tasks.TaskHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinsEarned")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("XpEarned")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.HasIndex("UserId");

                    b.ToTable("TaskHistories", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Tasks.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoinReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5);

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DeadlineValue")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<int>("Order")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoutineId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("XpReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.HasKey("Id");

                    b.HasIndex("RoutineId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Coins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsPremium")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("user");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Coins = 1000,
                            Email = "admin@rotinik.com",
                            IsPremium = true,
                            Name = "Administrador",
                            Password = "$2a$11$ah3WykwyffrfPRSXBSynZOnXqdFPrVjJeHB6vTmN47FIn1rPJ.9wq",
                            Points = 1000,
                            Role = "admin",
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Rotinik.Features.Users.UserRefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserRefreshTokens");
                });

            modelBuilder.Entity("Rotinik.Features.Wallet.WalletTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Currency")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("WalletTransactions", (string)null);
                });

            modelBuilder.Entity("Rotinik.Features.Medals.UserMedal", b =>
                {
                    b.HasOne("Medal", "Medal")
                        .WithMany()
                        .HasForeignKey("MedalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Routines.Routine", b =>
                {
                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Shop.UserShopItem", b =>
                {
                    b.HasOne("Rotinik.Features.Shop.ShopItem", "ShopItem")
                        .WithMany()
                        .HasForeignKey("ShopItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany("UserShopItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShopItem");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Statistics.DailyUserSummary", b =>
                {
                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Tasks.TaskHistory", b =>
                {
                    b.HasOne("Rotinik.Features.Tasks.TaskItem", "Task")
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Tasks.TaskItem", b =>
                {
                    b.HasOne("Rotinik.Features.Routines.Routine", "Routine")
                        .WithMany("Tasks")
                        .HasForeignKey("RoutineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Routine");
                });

            modelBuilder.Entity("Rotinik.Features.Users.UserRefreshToken", b =>
                {
                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Wallet.WalletTransaction", b =>
                {
                    b.HasOne("Rotinik.Features.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Rotinik.Features.Routines.Routine", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Rotinik.Features.Users.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserShopItems");
                });
#pragma warning restore 612, 618
        }
    }
}
